src/EdgeWeb/Project/UserBundle/Entity/User.php
<?php

namespace EdgeWeb\Project\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 */
class User extends BaseUser
{
    /**
     * @var integer
     */
   // private $id;
    protected $id;

    public function __construct()
    {
        parent::__construct();
        //your own logic here
    }

    /**
     * Get id
     *
     * @return integer
     */
    
    protected $roles = array();
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $timerecords;

    private $payrolls;

    private $rates;

    /**
     * @var \EdgeWeb\Project\EmployeeBundle\Entity\Position
     */
    private $position;


    /**
     * Add timerecord
     *
     * @param \EdgeWeb\Project\EmployeeBundle\Entity\Timerecord $timerecord
     *
     * @return User
     */
    public function addTimerecord(\EdgeWeb\Project\EmployeeBundle\Entity\Timerecord $timerecord)
    {
        $this->timerecords[] = $timerecord;

        return $this;
    }

    /**
     * Remove timerecord
     *
     * @param \EdgeWeb\Project\EmployeeBundle\Entity\Timerecord $timerecord
     */
    public function removeTimerecord(\EdgeWeb\Project\EmployeeBundle\Entity\Timerecord $timerecord)
    {
        $this->timerecords->removeElement($timerecord);
    }

    /**
     * Get timerecords
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTimerecords()
    {
        return $this->timerecords;
    }

     /**
     * Add payroll
     *
     * @param \EdgeWeb\Project\PaycomBundle\Entity\Payroll $payroll
     *
     * @return User
     */
    public function addPayroll(\EdgeWeb\Project\PaycomBundle\Entity\Payroll $payroll)
    {
        $this->payrolls[] = $payroll;

        return $this;
    }

    /**
     * Remove payroll
     *
     * @param \EdgeWeb\Project\PaycomBundle\Entity\Payroll $payroll
     */
    public function removePayroll(\EdgeWeb\Project\PaycomBundle\Entity\Payroll $payroll)
    {
        $this->payrolls->removeElement($payroll);
    }

    /**
     * Get payroll
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPayrolls()
    {
        return $this->payrolls;
    }


    /**
     * Set position
     *
     * @param \EdgeWeb\Project\EmployeeBundle\Entity\Position $position
     *
     * @return User
     */
    public function setPosition(\EdgeWeb\Project\EmployeeBundle\Entity\Position $position = null)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return \EdgeWeb\Project\EmployeeBundle\Entity\Position
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function getExpiresAt()
    {
        return $this->expiresAt;
    }
    public function getCredentialsExpireAt()
    {
        return $this->credentialsExpireAt;
    }
}

src/EdgeWeb/Project/UserBundle/Form/ProfileFormType.php
<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace EdgeWeb\Project\UserBundle\Form;

use FOS\UserBundle\Util\LegacyFormHelper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\Validator\Constraints\UserPassword;

class ProfileFormType extends AbstractType
{
    

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->buildUserForm($builder, $options);

        $builder->add('current_password', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\PasswordType'), array(
            'label' => 'form.current_password',
            'translation_domain' => 'FOSUserBundle',
            'mapped' => false,
            'constraints' => new UserPassword(),
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => $this->class,
            'csrf_token_id' => 'profile',
            // BC for SF < 2.8
            'intention'  => 'profile',
        ));
    }

    // BC for SF < 2.7
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $this->configureOptions($resolver);
    }

    // BC for SF < 3.0
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function getBlockPrefix()
    {
        return 'app_user_profile';
    }

    /**
     * Builds the embedded form representing the user.
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    protected function buildUserForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', null, array('label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
            ->add('email', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\EmailType'), array('label' => 'form.email', 'translation_domain' => 'FOSUserBundle'))
          //  ->add('enabled')
        ;
    }

    public function getParent()
    {
        //return 'FOS\UserBundle\Form\Type\ProfileFormType';

        // Or for Symfony < 2.8
         return 'fos_user_profile';
    }
}

src/EdgeWeb/Project/UserBundle/Controller/UserController.php
<?php

namespace EdgeWeb\Project\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use EdgeWeb\Project\EmployeeBundle\Entity\Comment;
use EdgeWeb\Project\EmployeeBundle\Entity\Task;
use EdgeWeb\Project\EmployeeBundle\Repository\TaskRepository;

class UserController extends Controller
{
    public function allUserAction()
    {
    	//$allUser = 'me';

    	$em = $this->getDoctrine()->getManager();

        $allUser = $em->getRepository('UserBundle:User')->findAll();

        return $this->render('UserBundle:User:allUser.html.twig', array(
           	'allUser' => $allUser
        ));    
    }

    public function showTransactionsAction(Request $request, $id)
    {
      
    	$em = $this->getDoctrine()->getManager();

        $user = $em->getRepository('UserBundle:User')->find($id);//find all user id


        $tasks = $em->getRepository('EmployeeBundle:Task')->getTasksForUser($user->getUsername());
          //paginator
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $tasks,
            $request->query->getInt('page', 1)/*page number*/,
            15/*limit per page*/
        );
     
        return $this->render('UserBundle:User:showTransactions.html.twig', array(
        	'transactions' => $pagination,
        	'username' => strtoupper($user->getUsername()),
        ));
    }
}

src/EdgeWeb/Project/UserBundle/Resources/views/User/allUser.html.twig
{% extends 'users/layout.html.twig' %}

{% block body_id 'admin_post_index' %}

{% block main %}
<h3>User</h3>
<table class="table table-hover">
	<thead>
		<tr>
			<th>Id</th>
			<th><i class="fa fa-users"></i>Username</th>
			<th><i class="fa fa-role"></i>Role</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for user in allUser %}
		<tr>
			<td>{{ user.id }}</td>
			<td>{{ user.username }}</td>
			<td>{% for roles in user.getRoles %}{{ roles }}{% endfor %}</td>
			<td>
				{% if user.isEnabled() == 1 %} 
					Active
				{% else %}
					Already Dead
				{% endif %}
			</td>
			<td>
				<div class="item-actions">
                    <a href={#{ path('fos_user_profile_edit')}#}><i class="fa fa-edit"></i>Edit</a>  
                   	  <a href="{{ path('users_task_show', { 'id': user.id }) }}" class="btn btn-sm btn-danger"><i class="fa fa-eye"></i>Tasks</a>
                </div>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

src/EdgeWeb/Project/UserBundle/Resources/views/User/showTransactions.html.twig
{% extends 'users/layout.html.twig' %}

{% block body_id 'admin_post_index' %}

{% block main %}
<h4>{{ username }} Has Total Tasks: {{ transactions.getTotalItemCount | number_format }} as of {{ 'now' | date('F d, Y h:i A') }}</h4>
{% if transactions|length > 0 %}
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Project Name</th>
				<th>Task Name</th>
				<th>Total Hours</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
			{% for transaction in transactions %}
			<tr>
				<td>{{ transaction.project }}</td>
				<td>{{ transaction.name }}</td>
				<td>{{ transaction.getWorkedHours() }}</td>
				<td>
					{% if transaction.datecreated %}
						{{ transaction.datecreated|date('Y-m-d h:i:s a') }}
					{% endif %}
				</td>
			</tr>
			{% endfor %}
		
		</tbody>
	</table>
{% else %}
	<p class="alert alert-warning">{{ username }} Has No Task created!</p>
{% endif %}
{# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(transactions) }}
    </div>
{% endblock %}